### DISCUSSION TITLE
Default Theme ( Github )

### DISCUSSION THREAD

**Discussion by setanarut** [sbarex/QLMarkdown#16] [General]
I'm overwriting to markdown.css.

## change log

- [x] Unused variables have been removed. Some of them are marked with a comment.
- [x] Original light colors
- [x] Original dark colors
- [x] Original dark syntax highlight colors
- [x] Original light syntax highlight colors
- [x] Set code block maximum width.
- [x] `<article>` tag
- [x] Original task list checkbox dark appearance

Completed 2021, Happy New Year

**Comment by sbarex** [comment]
Thansk, 
the css for the source code is generated by `highlight`. 

Depending on the source style adopted (and the language interpreted), the keywords can be more than 4. (from a to ... z?)

**Reply by setanarut** [reply]
maybe, I haven't read the highlight documentation yet. It takes a lot of time.

```css
.hl.kwa { color: var(--hl_Keyword-1); }
.hl.kwb { color: var(--hl_Keyword-2); }
.hl.kwc { color: var(--hl_Keyword-3); }
.hl.kwd { color: var(--hl_Keyword-4); }
.hl.kwe { color: var(--hl_Keyword-5); }
.hl.kwf { color: var(--hl_Keyword-6); }
```
