### ISSUE TITLE
Feature request: rendering of YAML header as table

### ISSUE THREAD

**Issue by akharrou** [sbarex/QLMarkdown#67]
Hello,

Would it be possible to have an option to render the YAML header part as a table, maybe separated with a horizontal rule (line) ? Or maybe you can come up with even better :D

E.g.:

YAML header:
```yaml
Title: My Title
Author: Steve jobs
Date: Tuesday, March 23, 2021
Abstract: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum."
```

Becomes (equivalent markdown rendering):
```md
|||
|-|-|
**Title** | My Title
**Author** | Steve jobs
**Date** | Tuesday, March 23, 2021
**Abstract** | "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quisque id diam vel quam elementum pulvinar. Orci nulla pellentesque dignissim enim. Magna fringilla urna porttitor rhoncus dolor purus. Mollis nunc sed id semper risus in hendrerit gravida rutrum."
```

Renders as:
![image](https://user-images.githubusercontent.com/36056254/117873992-1f57d880-b2a9-11eb-8dc7-2260fd4990e7.png)

---
I feel this is much more readable. Thank you so much for your extension !
