### ISSUE TITLE
Quick look for markdown files is shown with extra margin on Mac OS Monterey 12.0.1

### ISSUE THREAD

**Issue by olshevski** [sbarex/QLMarkdown#85]
After update to Mac OS Monterey QLMarkdown started showing md files with some unusual extra margin on left/right sides. Take a look at these screenshots. It wasn't like this on Big Sur. All other quick look plugins I've used so far render their output correctly.

![image](https://user-images.githubusercontent.com/5606565/146201495-8db2e517-eb80-483e-97bb-910ac6176e98.png)
![image](https://user-images.githubusercontent.com/5606565/146201538-5fb83971-9544-4ae6-ad37-93eabcf0ee8e.png)

**Comment by olshevski** [comment]
I'm using the latest version 1.0.6 of QLMarkdown.

**Comment by hazarek** [comment]
The default Quick-Look window size may be different in Monterey. These CSS settings mimic Github site.  
Here is the part about the margin;

https://github.com/sbarex/QLMarkdown/blob/c336438c51450b01288c1491c48a1f468b2aefd9/Resources/default.css#L150
https://github.com/sbarex/QLMarkdown/blob/c336438c51450b01288c1491c48a1f468b2aefd9/Resources/default.css#L160

```css
/* If the window is bigger than 902 pixels, the border will be visible. */
@media (min-width: 902px) {
  article {
    border-radius: 8px;
    border-width: 1px;  
    border-style: solid;
    border-color: var(--body-border-color);
  }
}

article {
  margin: auto;
  max-width: 902px;
  font-size: inherit;
  line-height: 1.5;
  word-wrap: break-word;
  padding: 32px;
}
```

## Menu related to CSS file

<img width="607" alt="Ekran Resmi 2021-12-15 20 35 02" src="https://user-images.githubusercontent.com/36481442/146236488-c2d61531-0bed-47dd-bdd1-4301939fdd16.png">
